module StratD
{

	struct Ressource
	{
		long type;
		long nb;
	};


	interface Producteur
	{
		boolean demandeRessource(in Ressource r);
		Ressource sondeProd();
		void annonce();
		oneway void lancementProduction();
	};


	typedef sequence<Producteur> tabProducteur;


	interface Joueur
	{
		typedef sequence<Joueur> tabJoueur;

//		boolean vole(in long n);
		void rcvListProd(in tabProducteur prod);
		void rcvListJoueur(in tabJoueur joueur);
		oneway void gameLoop();
		void joueTour();
	};


	interface Coordinateur
	{
		long ajoutJoueur(in Joueur j, in boolean RbR);
		long ajoutProd(in Producteur p);
		void ping(in long id);
		void finTour();
	};

};
